### ISSUE TITLE
Social Media icons

### ISSUE THREAD

**Issue by crusader2000** [OSDG-IIITH/astronomy-club-website#6]
The icons on the landing page are almost invisible.
Remove dribble , twitter and instagram logo and add a whatsapp and mail icons.
These should be added to the contact page and should be fairly visible. 
Suggestion : change to a icon theme  which has fb,whatsappa and mail logos

![Screenshot from 2020-05-19 16-35-41](https://user-images.githubusercontent.com/43775333/82318688-e36b9980-99ed-11ea-99af-c6447c4b7734.png)

**Comment by dkapur17** [comment]
By added do you mean removed from the homepage and added to contacts, or should be there on both the pages?

**Comment by crusader2000** [comment]
Remove from homepage and add to contacts page
